{% set name = "sridentify" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sridentify-{{ version }}.tar.gz
  sha256: 4fff6ed32f27ccb2c7d4bc839bfa4c5e5792f25b37cad835c027b5afafa94be2

build:
  number: 1
  noarch: python
  entry_points:
    - sridentify=sridentify.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - sridentify
  commands:
    - pip check
    - sridentify --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cmollet/sridentify
  summary: Identify the EPSG code from a .prj file
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - getiria-onsongo
